exclude: 'config.yaml|config_examples/.*.yaml|hera_sim/config/H1C.yaml|hera_sim/config/H2C.yaml|setup.py|hera_sim/tests/testdata/hera-sim-vis-config/NF_HERA_Dipole_small.fits'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  # - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']  # Only check syntax rather than try to load.
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-rst-docstrings
          #- flake8-docstrings  # not available for flake8>5
          - flake8-builtins
          - flake8-logging-format
          - flake8-rst-docstrings
          - flake8-rst
#          - flake8-markdown    # not available for flake8>5 (check later...)
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-print
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/asottile/pyupgrade
  rev: v3.9.0
  hooks:
  - id: pyupgrade
    args: [--py39-plus]

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.4.0
  hooks:
  - id: setup-cfg-fmt