filing:
    outdir: '.'
    outfile_name: 'temporary'
    output_format: 'uvh5'
    clobber: True
    kwargs: {}
freq:
    Nfreqs: 50
    channel_width: 122070.3125
    start_freq: 100234567.333
time:
    Ntimes: 10
    integration_time: 8.59
    start_time: 2457458.174
telescope:
    array_layout: !antpos
        array_type: hex
        hex_num: 3
        sep: 14.6
        split_core: False
        outriggers: 0
    omega_p: !Beam
        datafile: HERA_H2C_BEAM_MODEL.npz
        interp_kwargs:
            interpolator: interp1d
            fill_value: extrapolate
sky:
    Tsky_mdl: !Tsky
        datafile: HERA_Tsky_Reformatted.npz
        interp_kwargs:
            pol: xx
    eor:
        noiselike_eor: {}
    foregrounds:
        diffuse_foreground: {}
        pntsrc_foreground: {}
systematics:
    rfi:
        rfi_stations: {}
        rfi_impulse: {}
        rfi_scatter: {}
        rfi_dtv: {}
    sigchain:
        gains: {}
    crosstalk:
        gen_whitenoise_xtalk: {}
simulation:
    components:
        - "foregrounds"
#        - "rfi"
        - "sigchain"
    exclude: []
