# minimum-spec development environment for travis

name: test-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - aipy>=3.0
  - attrs
  - h5py
  - hdf5
  - healpy
  - nose
  - numpy
  - pip
  - pytest
  - pyuvdata
  - scipy
  - pyyaml
  - psutil
  - git+https://github.com/RadioAstronomySoftwareGroup/healvis.git
  - future #only for python 2
  - pip:
    - cached-property
    - git+https://github.com/RadioAstronomySoftwareGroup/pyuvsim.git
    - git+https://github.com/HERA-Team/uvtools.git
