# minimum-spec development environment for travis

name: test-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - aipy=3.0.0rc2
  - attrs
  - h5py
  - hdf5
  - healpy
  - mpi4py
  - nose
  - numpy
  - pip
  - pytest-cov
  - pyuvdata
  - scipy
  - pyyaml
  - psutil
  - astropy
  - numba
  - future #only for python 2
  - pip:
    - cached-property
    - pyuvsim
    - git+https://github.com/HERA-Team/uvtools.git
    - git+https://github.com/radioastronomysoftwaregroup/healvis
    - pip install git+https://github.com/RadioAstronomySoftwareGroup/pyuvsim.git

