# minimum-spec development environment for travis

name: test-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - aipy>=3.0
  - attrs
  - click
  - h5py
  - hdf5
  - healpy
  - nose
  - numpy
  - pip
  - pytest-cov
  - scipy
  - pyyaml
  - future # only for python 2
  - numba
  - psutil
  - astropy-healpix
  - basemap
  - pip:
    - cached-property
    - git+https://github.com/RadioAstronomySoftwareGroup/pyuvsim.git
    - git+https://github.com/RadioAstronomySoftwareGroup/pyradiosky.git
    - git+https://github.com/RadioAstronomySoftwareGroup/pyuvdata.git
    - git+https://github.com/HERA-Team/uvtools.git
    - git+https://github.com/rasg-affiliates/healvis
    - astropy-healpix
    - git+https://github.com/HERA-Team/hera_cal.git
