# minimum-spec development environment for travis

name: test-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - aipy=3.0.0rc2
  - attrs
  - h5py
  - hdf5
  - healpy
  - mpi4py
  - nose
  - numpy
  - pip
  - pytest
  - pyuvdata
  - scipy
  - pyyaml
  - pip:
    - cached-property
    - pyuvsim
    - git+https://github.com/HERA-Team/uvtools.git
