setup:
    frequency_array:
        Nfreqs: 10
        channel_width: 97656.25
        start_freq: 100000000
    time_array:
        Ntimes: 20
        integration_time: 10.7
        start_time: 2458119.5
telescope:
    array_layout: !antpos
        array_type: linear
        nants: 2
        sep: 14.6
    bp_poly: !Bandpass
        datafile: HERA_H1C_BANDPASS.npy
        interp_kwargs:
            interpolator: poly1d
    omega_p: !Beam
        datafile: HERA_H1C_BEAM_POLY.npy
        interp_kwargs:
            interpolator: poly1d
    delay_filter_type: tophat
    fringe_filter_type: tophat
sky:
    Tsky_mdl: !Tsky
        datafile: HERA_Tsky_Reformatted.npz
        interp_kwargs:
            pol: xx
