# This document is intended to serve as a template for constructing new
# configuration YAMLs for use with the `simulate.py` script. This version
# is intended to be used with the version 0.x.x release of `hera_sim`. For
# v1.x.x, please use the other template in this directory.

bda_params:
    apply_bda: True
    max_decorr: 0
    pre_fs_int_time: 
        value: 0
        units: s
    corr_FoV_angle:
        value: 0
        units: deg
    max_time:
        value: 0
        units: s
    corr_int_time:
        value: !!null
        units: s
