# This document is intended to serve as a template for constructing new
# configuration YAMLs for use with the `simulate.py` script. This version
# is intended to be used with the version 1 release of `hera_sim`. For 
# older versions of `hera_sim`, use the template labeled as `old`.


