# This document is intended to serve as a template for constructing new
# configuration YAMLs for use with the `simulate.py` script. This version
# is intended to be used with the version 0.x.x release of `hera_sim`. For
# v1.x.x, please use the other template in this directory.

# XXX do we want this to be an exhaustive template (all possible things
# specified), or do we want this to be a minimal template?

bda:
    apply_bda: True
    max_decorr: 0
    pre_fs_int_time: !dimensionful 
        value: 0
        units: 's'
    corr_FoV_angle: !dimensionful
        value: 0
        units: 'deg'
    max_time: !dimensionful
        value: 0
        units: 's'
    corr_int_time: !dimensionful
        value: !!null
        units: 's'
filing:
    outdir: '.'
    outfile_name: 'quick_and_dirty_sim'
    output_format: 'uvh5'
    clobber: False
freq:
    Nfreqs: 1024
    channel_width: 122070.3125
    start_freq: 46920776.3671875
time:
    Ntimes: 10
    integration_time: 8.59
    start_time: 2457458.1738949567
telescope:
    array_layout: 'antenna_layout.csv'
    # TODO: allow use with hera_sim.antpos
    # alternatively can specify how to construct it with hera_sim.antpos
systematics:
    # TODO: fill out what should go in here
analysis:
    # TODO: fill out what should go in here
